version: "3.9"
services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
